### ISSUE TITLE
Tomcat connector in failed state

### ISSUE THREAD

**Issue by alchemistgo87** [AndreasKl/springboot-angular-atmosphere-quickstart#3] opened 2015-08-13 20:24 UTC
while running the code it gives following error:

```
Exception in thread "main" java.lang.IllegalStateException: Tomcat connector in failed state
    at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:157)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:287)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:691)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
    at net.andreaskluth.toastonatmosphere.Application.main(Application.java:19)
```

**Comment by AndreasKl** [comment] 2015-08-14 13:41
@alchemistgo87 could you post the whole stacktrace? The cause usually is another application using the same http port.

**Comment by alchemistgo87** [comment] 2015-08-14 21:06
I guess you are correct. It was due to another application using the port 8080. Fixed it. Thank you.

**Comment by AndreasKl** [comment] 2015-08-14 21:22
Perfect, closing. Feel free to open a new ticket if you observe any issues.

**Comment by alchemistgo87** [comment] 2015-08-14 21:23
By the way can you tell how it works? I go to the url: http://localhost:8080/broadcast/MyMessage and it shows me login screen, I login and the screen goes blank.

**Closed as completed by AndreasKl** 2015-08-14 21:22 UTC

**Comment by AndreasKl** [comment] 2015-08-14 21:34
Sure, the broadcast endpoint just submits messages. With a GET request on `http://localhost:8080/broadcast/MyMessage` you send MyMessage to all registered consumers. To open a consumer just open `http://localhost:8080/` (without the broadcast) in another tab or browser, this should load a small angualr app.

**Comment by alchemistgo87** [comment] 2015-08-14 21:38
I did the same, but after I open http://localhost:8080/ it just shows: "Call /broadcast/{argument} to broadcast to all logged in users.Template served by Angular {{version}}." There are no messages.

**Comment by AndreasKl** [comment] 2015-08-14 22:01
If the `{{version}}` placeholder is not set then the angular frontend is not properly executed. Could you check if all resources are loaded (you could have a look in the dev console of your browser).. As I wrote this sample a year ago and did the last update half a year ago I'll check whether all parts are still working.

I reactivated the app on giant swarm, so at least the docker image works: http://andreas.gigantic.io/login
